# Generated by Django 5.2.12 on 2026-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="GST % charged to customer, goes to govt",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Shipping/packaging — company keeps",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="other_charges_type",
            field=models.CharField(
                choices=[
                    ("flat", "Flat amount"),
                    ("percent", "Percentage of selling price"),
                ],
                default="flat",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pricing_configured",
            field=models.BooleanField(
                default=False, help_text="True when admin has set pricing"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost company pays to procure",
                max_digits=10,
                null=True,
            ),
        ),
    ]
