# Generated by Django 5.2.12 on 2026-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0002_product_gst_percentage_product_other_charges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost to procure this variant",
                max_digits=10,
                null=True,
            ),
        ),
    ]
