# Generated by Django 5.2.12 on 2026-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0003_productvariant_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="upa_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated UPA price after discount",
                max_digits=10,
                null=True,
            ),
        ),
    ]
