# Generated by Django 5.2.12 on 2026-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0004_productvariant_upa_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
