# Generated by Django 5.2.12 on 2026-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0007_productvariant_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Synced from lowest variant MRP when pricing is set",
                max_digits=12,
                null=True,
            ),
        ),
    ]
