# Generated by Django 5.2.12 on 2026-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysettings",
            name="default_proof_type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo only"),
                    ("otp", "OTP only"),
                    ("either", "Either"),
                ],
                default="either",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deliverysettings",
            name="max_orders_per_partner",
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="deliverysettings",
            name="assignment_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual — I'll assign every order myself"),
                    ("suggested", "Suggested — System suggests, I confirm"),
                    ("automatic", "Automatic — System assigns instantly"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
