# Generated by Django 5.2.12 on 2026-07-02 19:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_fix_stale_assignment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="duty_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="is_on_duty",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DutyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("on_duty", "On Duty"), ("off_duty", "Off Duty")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("date", models.DateField()),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_logs",
                        to="delivery.deliverypartner",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["partner", "date"],
                        name="delivery_du_partner_98ddcd_idx",
                    )
                ],
            },
        ),
    ]
