# Generated by Django 5.2.12 on 2026-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_duty_log_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysettings",
            name="count_half_days",
            field=models.BooleanField(
                default=True,
                help_text="If OFF, only Full Day or Absent — no half day status",
            ),
        ),
        migrations.AddField(
            model_name="deliverysettings",
            name="full_day_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=6.0,
                help_text="Minimum hours to count as a full day. Default: 6.0 hours",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="deliverysettings",
            name="half_day_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=3.0,
                help_text="Minimum hours to count as a half day. Default: 3.0 hours",
                max_digits=4,
            ),
        ),
    ]
