# Generated by Django 5.2.12 on 2026-07-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_deliverysettings_count_half_days_and_more"),
        ("orders", "0009_order_is_offline_order_order_type_and_more"),
        ("returns", "0005_alter_returnrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("order", "Order Delivery"),
                    ("exchange", "Exchange Delivery"),
                ],
                default="order",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="exchange_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_delivery",
                to="returns.returnrequest",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryassignment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_assignment",
                to="orders.order",
            ),
        ),
    ]
