# Generated by Django 5.2.12 on 2026-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_rejection_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
