# Generated by Django 5.2.12 on 2026-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_is_satisfied_order_satisfied_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="gst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="other_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
