# Generated by Django 5.2.12 on 2026-06-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderitem_gst_amount_orderitem_other_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[("upa", "UPA"), ("regular", "Regular")],
                default="regular",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
