services:
  - type: web
    name: my-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:10000 --workers 2 --timeout 120"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0