# Generated by Django 5.2.12 on 2026-05-30 20:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0006_orderitem_return_rejection_count"),
        ("app_products", "0001_initial"),
        ("app_wallet", "0002_wallettransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionBreakup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_base_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("network_pool", models.DecimalField(decimal_places=2, max_digits=12)),
                ("team_pool", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_window", "Waiting for return window"),
                            ("processing", "Being processed"),
                            ("completed", "All credits done"),
                            ("partial", "Some pending"),
                        ],
                        default="pending_window",
                        max_length=15,
                    ),
                ),
                ("return_window_expires", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_breakup",
                        to="orders.OrderItem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommissionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_upa_id", models.CharField(blank=True, max_length=20)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                ("recipient_mobile", models.CharField(blank=True, max_length=20)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("network_upline", "Network (upline)"),
                            ("team_downline", "Team (downline)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("level", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "leg_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("middle", "Middle"),
                            ("right", "Right"),
                        ],
                        max_length=6,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "percentage_applied",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("credited", "Credited to wallet"),
                            ("pending", "Pending — user inactive"),
                            ("vacant", "Vacant leg — skipped"),
                        ],
                        max_length=8,
                    ),
                ),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "breakup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="commissions.commissionbreakup",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_wallet.WalletTransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommissionSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "network_commission_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("7.00"), max_digits=5
                    ),
                ),
                (
                    "team_commission_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=5
                    ),
                ),
                ("max_upline_levels", models.PositiveIntegerField(default=7)),
                ("use_max_levels", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("top_heavy", "L1 gets most (direct parent)"),
                            ("bottom_heavy", "L7 gets most (root)"),
                        ],
                        default="top_heavy",
                        max_length=12,
                    ),
                ),
                ("level_percentages", models.JSONField(default=list)),
                (
                    "left_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=5
                    ),
                ),
                (
                    "middle_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                (
                    "right_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                (
                    "trigger_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto after return window expires"),
                            ("manual", "Manual by admin"),
                        ],
                        default="auto",
                        max_length=6,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Settings",
                "verbose_name_plural": "Commission Settings",
            },
        ),
        migrations.CreateModel(
            name="ProductCommissionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "network_commission_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "team_commission_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("max_upline_levels", models.PositiveIntegerField(default=7)),
                ("use_max_levels", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("top_heavy", "L1 gets most (direct parent)"),
                            ("bottom_heavy", "L7 gets most (root)"),
                        ],
                        default="top_heavy",
                        max_length=12,
                    ),
                ),
                ("level_percentages", models.JSONField(default=list)),
                (
                    "left_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=5
                    ),
                ),
                (
                    "middle_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                (
                    "right_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_commission_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rule",
                        to="app_products.Product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
