# Generated by Django 5.2.12 on 2026-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_window", "Pending return window"),
                    ("credited", "Credited to wallet"),
                    ("pending", "Pending — user inactive"),
                    ("vacant", "Vacant leg — skipped"),
                ],
                max_length=14,
            ),
        ),
    ]
