# Generated by Django 5.2.12 on 2026-06-03 19:49

from django.db import migrations, models


def migrate_direction_values(apps, schema_editor):
    CommissionSettings = apps.get_model('commissions', 'CommissionSettings')
    ProductCommissionRule = apps.get_model('commissions', 'ProductCommissionRule')
    CommissionSettings.objects.filter(direction='top_heavy').update(direction='direct_first')
    CommissionSettings.objects.filter(direction='bottom_heavy').update(direction='ancestor_first')
    ProductCommissionRule.objects.filter(direction='top_heavy').update(direction='direct_first')
    ProductCommissionRule.objects.filter(direction='bottom_heavy').update(direction='ancestor_first')


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0002_alter_commissionentry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionsettings",
            name="company_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% of profit for company",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="commissionsettings",
            name="social_work_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% of profit for social work fund",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="productcommissionrule",
            name="company_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="productcommissionrule",
            name="social_work_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        # Increase max_length BEFORE data migration so 'ancestor_first' (13 chars) fits
        migrations.AlterField(
            model_name="commissionsettings",
            name="direction",
            field=models.CharField(
                choices=[
                    ("direct_first", "Direct parent gets most"),
                    ("ancestor_first", "Top ancestor gets most"),
                ],
                default="direct_first",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productcommissionrule",
            name="direction",
            field=models.CharField(
                choices=[
                    ("direct_first", "Direct parent gets most"),
                    ("ancestor_first", "Top ancestor gets most"),
                ],
                default="direct_first",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_direction_values, migrations.RunPython.noop),
    ]
