# Generated by Django 5.2.12 on 2026-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0003_add_social_work_company_pct_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionbreakup",
            name="rule_snapshot",
            field=models.JSONField(
                default=dict,
                help_text="Snapshot of commission rule at calculation time",
            ),
        ),
        migrations.AlterField(
            model_name="commissionentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("network_upline", "Network (upline)"),
                    ("team_downline", "Team (downline)"),
                    ("social_work", "Social Work"),
                    ("company", "Company"),
                ],
                max_length=20,
            ),
        ),
    ]
