# Generated by Django 5.2.12 on 2026-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0004_commissionbreakup_rule_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionsettings",
            name="delivery_packaging_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="commissionsettings",
            name="self_commission_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commissionsettings",
            name="self_commission_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="productcommissionrule",
            name="delivery_packaging_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="productcommissionrule",
            name="self_commission_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcommissionrule",
            name="self_commission_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="commissionentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("network_upline", "Network (upline)"),
                    ("team_downline", "Team (downline)"),
                    ("social_work", "Social Work"),
                    ("company", "Company"),
                    ("self_commission", "Self Commission"),
                ],
                max_length=20,
            ),
        ),
    ]
