# Generated by Django 5.2.12 on 2026-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0005_commissionsettings_delivery_packaging_pct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_window", "Pending return window"),
                    ("credited", "Credited to wallet"),
                    ("pending", "Pending — user inactive"),
                    ("vacant", "Vacant leg — skipped"),
                    ("ignored", "Ignored by admin"),
                ],
                max_length=14,
            ),
        ),
    ]
