# Generated by Django 5.2.12 on 2026-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0006_alter_commissionentry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionbreakup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_window", "Waiting for return window"),
                    ("exchange_hold", "On hold — exchange buffer"),
                    ("processing", "Being processed"),
                    ("completed", "All credits done"),
                    ("partial", "Some pending"),
                    ("cancelled", "Cancelled — item returned"),
                ],
                default="pending_window",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="commissionentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_window", "Pending return window"),
                    ("credited", "Credited to wallet"),
                    ("pending", "Pending — user inactive"),
                    ("vacant", "Vacant leg — skipped"),
                    ("ignored", "Ignored by admin"),
                    ("cancelled", "Cancelled — item returned"),
                ],
                max_length=14,
            ),
        ),
    ]
