# Generated by Django 5.2.12 on 2026-07-26 16:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_products", "0004_productvariant_upa_price"),
        ("commissions", "0007_exchange_buffer_and_commission_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantCommissionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "network_commission_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "team_commission_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "social_work_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "company_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("max_upline_levels", models.PositiveIntegerField(default=7)),
                ("use_max_levels", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("direct_first", "Direct parent gets most"),
                            ("ancestor_first", "Top ancestor gets most"),
                        ],
                        default="direct_first",
                        max_length=20,
                    ),
                ),
                ("level_percentages", models.JSONField(default=list)),
                (
                    "left_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=5
                    ),
                ),
                (
                    "middle_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                (
                    "right_leg_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=5
                    ),
                ),
                ("self_commission_enabled", models.BooleanField(default=False)),
                (
                    "self_commission_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "delivery_packaging_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_variant_commission_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rule",
                        to="app_products.productvariant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
