# Generated by Django 5.2.12 on 2026-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="user_reply_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
