# Generated by Django 5.2.12 on 2026-03-23 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0002_returnrequest_user_reply_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="attempt_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="waiting_for",
            field=models.CharField(
                blank=True,
                choices=[("admin", "Admin"), ("user", "User"), ("", "Nobody")],
                default="admin",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="returnsettings",
            name="max_attempts",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("raised", "Raised"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("rejected_final", "Rejected Final"),
                    ("completed", "Completed"),
                ],
                default="raised",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("info_requested", "Info Requested"),
                            ("user_replied", "User Replied"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("rejected_final", "Rejected Final"),
                            ("re_raised", "Re-raised"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_log_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="returnphoto",
            name="log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="returns.returnrequestlog",
            ),
        ),
    ]
