# Generated by Django 5.2.12 on 2026-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0003_add_log_model_waiting_for_attempt_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnsettings",
            name="exchange_buffer_days",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
