# Generated by Django 5.2.12 on 2026-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0004_exchange_buffer_and_commission_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("raised", "Raised"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("exchange_dispatched", "Exchange Dispatched"),
                    ("rejected", "Rejected"),
                    ("rejected_final", "Rejected Final"),
                    ("completed", "Completed"),
                ],
                default="raised",
                max_length=20,
            ),
        ),
    ]
