# Generated by Django 5.2.12 on 2026-06-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("employee", "Employee"),
                    ("upa_user", "UPA User"),
                    ("vendor", "Vendor"),
                    ("delivery_partner", "Delivery Partner"),
                ],
                default="upa_user",
                max_length=20,
            ),
        ),
    ]
