from datetime import date

from django.db import transaction
from django.utils import timezone


REJECTION_REASONS = {
    'damaged_packaging': 'Damaged packaging',
    'product_defective': 'Product defective',
    'wrong_product':     'Wrong product received',
    'quantity_mismatch': 'Quantity mismatch',
    'expired':           'Expired / near expiry',
    'other':             'Other',
}


def generate_debit_note_pdf(report):
    """Generate a debit note PDF using reportlab and save it to report.debit_note."""
    try:
        from io import BytesIO

        from django.core.files.base import ContentFile
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except ImportError:
        return  # reportlab not installed

    po      = report.shipment.purchase_order
    vendor  = po.vendor
    product = po.product

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=2 * cm, leftMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )

    styles     = getSampleStyleSheet()
    title_sty  = ParagraphStyle('dn_title',  parent=styles['Heading1'], fontSize=18, spaceAfter=4)
    sep_sty    = ParagraphStyle('dn_sep',    parent=styles['Normal'],   fontSize=9, textColor=colors.grey)
    sec_sty    = ParagraphStyle('dn_sec',    parent=styles['Normal'],   fontSize=11, fontName='Helvetica-Bold', spaceBefore=8, spaceAfter=4)
    footer_sty = ParagraphStyle('dn_footer', parent=styles['Normal'],   fontSize=8, textColor=colors.grey)
    normal     = styles['Normal']

    TBL = TableStyle([
        ('FONTNAME',      (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE',      (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ])
    TBL_KEY = TableStyle([
        ('FONTNAME',      (0, 0), (-1, -1), 'Helvetica'),
        ('FONTNAME',      (0, 0), (0, -1),  'Helvetica-Bold'),
        ('FONTSIZE',      (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ])

    elements = [
        Paragraph('DEBIT NOTE', title_sty),
        Paragraph('─' * 72, sep_sty),
        Spacer(1, 0.3 * cm),
    ]

    info = Table([
        ['PO Number:', po.po_number],
        ['Date:',      date.today().strftime('%d %b %Y')],
        ['Vendor:',    vendor.company_name],
        ['Product:',   product.name],
    ], colWidths=[4 * cm, 13 * cm])
    info.setStyle(TBL_KEY)
    elements.append(info)
    elements.append(Spacer(1, 0.4 * cm))

    elements.append(Paragraph('Shipment Summary:', sec_sty))
    summary = Table([
        ['Expected:',  f'{report.shipment.expected_quantity} units'],
        ['Received:',  f'{report.received_quantity} units'],
        ['Accepted:',  f'{report.accepted_quantity} units'],
        ['Rejected:',  f'{report.rejected_quantity} units'],
        ['Missing:',   f'{report.missing_quantity} units'],
    ], colWidths=[4 * cm, 13 * cm])
    summary.setStyle(TBL)
    elements.append(summary)

    if report.rejection_breakdown:
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph('Rejection Breakdown:', sec_sty))
        bd_rows = [
            [f'  {REJECTION_REASONS.get(k, k)}:', f'{v} units']
            for k, v in report.rejection_breakdown.items()
        ]
        bd_table = Table(bd_rows, colWidths=[8 * cm, 9 * cm])
        bd_table.setStyle(TBL)
        elements.append(bd_table)

    elements.append(Spacer(1, 0.4 * cm))
    elements.append(Paragraph('Estimated Debit Value:', sec_sty))
    debit_val = report.rejected_quantity * po.price_per_unit
    val_table = Table([
        [f'{report.rejected_quantity} units × ₹{po.price_per_unit}/unit', f'= ₹{debit_val:,.2f}'],
    ], colWidths=[9 * cm, 8 * cm])
    val_table.setStyle(TBL)
    elements.append(val_table)

    if report.general_notes:
        elements.append(Spacer(1, 0.3 * cm))
        elements.append(Paragraph(f'Notes: {report.general_notes}', normal))

    elements += [
        Spacer(1, 0.5 * cm),
        Paragraph('─' * 72, sep_sty),
        Paragraph('Auto-generated by the system.', footer_sty),
    ]

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    filename = f'DN-{po.po_number}.pdf'
    report.debit_note.save(filename, ContentFile(pdf_bytes), save=False)
    report.debit_note_generated_at = timezone.now()
    report.save(update_fields=['debit_note', 'debit_note_generated_at'])


def update_product_stock(report, updated_by, rack=None):
    """
    Add accepted_quantity to stock.
    If rack is provided, assigns to that rack and creates StockMovement.
    Otherwise falls back to direct variant stock_quantity increment.
    Marks report stock_updated and PO completed.
    """
    with transaction.atomic():
        po      = report.shipment.purchase_order
        product = po.product
        variant = product.variants.filter(is_active=True).first()
        if variant:
            if rack is not None:
                from apps.warehouse.utils import assign_stock_to_rack
                assign_stock_to_rack(
                    rack=rack,
                    variant=variant,
                    quantity=report.accepted_quantity,
                    performed_by=updated_by,
                    reference=po.po_number,
                    notes=f'Inspection stock update for {po.po_number}',
                )
            else:
                variant.stock_quantity += report.accepted_quantity
                variant.save(update_fields=['stock_quantity'])
        report.stock_updated    = True
        report.stock_updated_at = timezone.now()
        report.stock_updated_by = updated_by
        report.save(update_fields=['stock_updated', 'stock_updated_at', 'stock_updated_by'])
        po.status = 'completed'
        po.save(update_fields=['status'])
