# Generated by Django 5.2.12 on 2026-06-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_billing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_orders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_procurement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_products",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_returns",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_tenders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_vendors",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_manage_warehouse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="can_view_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="needs_system_access",
            field=models.BooleanField(
                default=False,
                help_text="True = can log in to the system. False = payroll only, no login needed.",
            ),
        ),
    ]
