# Generated by Django 5.2.12 on 2026-07-10 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_employeeprofile_can_manage_billing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("leave", "Leave"),
                            ("holiday", "Holiday"),
                            ("week_off", "Week Off"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casual", "Casual"),
                            ("sick", "Sick"),
                            ("earned", "Earned"),
                            ("unpaid", "Unpaid"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="payroll.employeeprofile",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "casual_leave",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "sick_leave",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "earned_leave",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="payroll.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("employee", "year")},
            },
        ),
    ]
