# Generated by Django 5.2.12 on 2026-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("order_received", "Order Received"),
                    ("commission_paid", "Commission Paid"),
                    ("refund_paid", "Refund Paid"),
                    ("gst_collected", "GST Collected"),
                    ("gst_paid", "GST Paid"),
                    ("manual_credit", "Manual Credit"),
                    ("manual_debit", "Manual Debit"),
                    ("salary_paid", "Salary Paid"),
                ],
                max_length=20,
            ),
        ),
    ]
