# Generated by Django 5.2.12 on 2026-03-28 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingShipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expected_quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_inspection", "Awaiting Inspection"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="awaiting_inspection",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("received_quantity", models.PositiveIntegerField()),
                ("accepted_quantity", models.PositiveIntegerField()),
                ("rejected_quantity", models.PositiveIntegerField()),
                ("missing_quantity", models.PositiveIntegerField()),
                ("rejection_breakdown", models.JSONField(default=dict)),
                ("rejection_other_notes", models.TextField(blank=True)),
                ("general_notes", models.TextField(blank=True)),
                ("inspected_at", models.DateTimeField(auto_now_add=True)),
                ("stock_updated", models.BooleanField(default=False)),
                ("stock_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "debit_note",
                    models.FileField(blank=True, null=True, upload_to="debit_notes/"),
                ),
                (
                    "debit_note_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report",
                        to="inspection.incomingshipment",
                    ),
                ),
                (
                    "stock_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_stock_update", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Settings",
                "verbose_name_plural": "Inspection Settings",
            },
        ),
    ]
